version: '3'

services:
  makemkv:
    build: .
    container_name: makemkv
    volumes:
      - ./input:/input     # Mount input directory for VIDEO_TS folders
      - ./output:/output   # Mount output directory
    # Run with interactive TTY - needed for MakeMKV CLI
    tty: true
    stdin_open: true
    restart: unless-stopped 